# Generated by Django 2.2.9 on 2020-01-30 07:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('points', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=255)),
                ('sumber', models.CharField(max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
            },
        ),
    ]
