# Generated by Django 2.2.9 on 2020-07-30 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=250)),
                ('lcode', models.CharField(max_length=20)),
                ('wadmkk', models.CharField(max_length=100)),
                ('wadmpr', models.CharField(max_length=100)),
                ('wiadkk', models.CharField(max_length=100)),
                ('shp_area', models.FloatField()),
                ('shp', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Administrasi',
                'ordering': ('namobj',),
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('points', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namrjl', models.CharField(max_length=100)),
                ('lcode', models.CharField(max_length=50)),
                ('spcrjl', models.CharField(choices=[('1', 'Freeway'), ('2', 'Highway'), ('3', 'Moderate road'), ('4', 'Small road'), ('0', 'Other')], max_length=1)),
                ('starjl', models.CharField(choices=[('1', 'Operational'), ('2', 'Will be built'), ('3', 'Under construction'), ('4', 'No longer used'), ('0', 'Other')], max_length=1)),
                ('utkrjl', models.CharField(choices=[('1', 'Public roads'), ('2', 'Special roads'), ('0', 'Other')], max_length=1)),
                ('wlyrjl', models.CharField(choices=[('1', 'Urban roads'), ('2', 'Rural roads'), ('0', 'Other')], max_length=1)),
                ('shp_length', models.FloatField()),
                ('lines', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Street',
                'ordering': ('utkrjl',),
            },
        ),
    ]
