# Generated by Django 2.2.9 on 2020-01-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinsi',
            name='slug',
        ),
    ]
