# Generated by Django 2.2.9 on 2020-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='spcrjl',
            field=models.CharField(choices=[('Freeway', 'Freeway'), ('Highway', 'Highway'), ('Moderate road', 'Moderate road'), ('Small road', 'Small road'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='street',
            name='starjl',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Will be built', 'Will be built'), ('Under construction', 'Under construction'), ('No longer used', 'No longer used'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='street',
            name='utkrjl',
            field=models.CharField(choices=[('Public roads', 'Public roads'), ('Special roads', 'Special roads'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='street',
            name='wlyrjl',
            field=models.CharField(choices=[('Urban roads', 'Urban roads'), ('Rural roads', 'Rural roads'), ('Other', 'Other')], max_length=20),
        ),
    ]
