# Generated by Django 2.2.9 on 2020-07-17 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('lines', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Street',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Lines',
        ),
    ]
