# Generated by Django 2.2.9 on 2020-05-01 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('lines', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Lines',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objname', models.CharField(max_length=100)),
                ('wadmkk', models.CharField(max_length=100)),
                ('wadmpr', models.CharField(max_length=100)),
                ('shp', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Shapefile',
                'ordering': ('objname',),
            },
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
        migrations.RemoveField(
            model_name='point',
            name='slug',
        ),
    ]
