# Generated by Django 2.2.9 on 2020-07-25 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200717_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='shp',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='street',
            name='lines',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326),
        ),
    ]
