# Generated by Django 2.2.9 on 2020-07-31 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200730_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=250)),
                ('lcode', models.CharField(max_length=20)),
                ('fgdpdk', models.CharField(choices=[('College', 'College'), ('Senior secondary Education (SMA, MA, SMALB)', 'Senior secondary Education (SMA, MA, SMALB)'), ('Vocational secondary education (SMK, MAK)', 'Vocational secondary education (SMK, MAK)'), ('First secondary education (SMP, MTs, SMPLB)', 'First secondary education (SMP, MTs, SMPLB)'), ('Primary education (SD, MI, SDLB)', 'Primary education (SD, MI, SDLB)'), ('Early childhood Education (TK, RA, TPA, KB)', 'Early childhood Education (TK, RA, TPA, KB)'), ('Course Board', 'Course Board'), ('Training Institute', 'Training Institute'), ('Community Learning Activities Center', 'Community Learning Activities Center'), ('Religious Education (Pesantren, Pasraman, etc.)', 'Religious Education (Pesantren, Pasraman, etc.)'), ('Other', 'Other')], max_length=50)),
                ('jnspdk', models.CharField(choices=[('General education', 'General education'), ('Vocational education', 'Vocational education'), ('Academic education', 'Academic education'), ('Professional education', 'Professional education'), ('Religious education', 'Religious education'), ('Special education', 'Special education'), ('Special Service Education', 'Special Service Education'), ('Other', 'Other')], max_length=30)),
                ('points', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Education Building',
                'ordering': ('namobj',),
            },
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AlterField(
            model_name='street',
            name='lcode',
            field=models.CharField(max_length=20),
        ),
    ]
