# Generated by Django 2.2.9 on 2020-03-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_provinsi_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provinsi',
        ),
    ]
