# Generated by Django 2.2.9 on 2020-07-30 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200725_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=250)),
                ('lcode', models.CharField(max_length=20)),
                ('wadmkk', models.CharField(max_length=100)),
                ('wadmpr', models.CharField(max_length=100)),
                ('wiadkk', models.CharField(max_length=100)),
                ('shp_area', models.FloatField()),
                ('shp', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
        migrations.AlterField(
            model_name='street',
            name='lines',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
